modLoader = "javafml"
loaderVersion = "[2,)"
license = "MIT"

[[mods]]
    modId = "cropaura"
    version = "1.0.0"
    displayName = "Crop Aura"
    description = '''
Automatically applies bonemeal to crops around the player.
    '''

[[dependencies.cropaura]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.1,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cropaura]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.1,1.22)"
    ordering = "NONE"
    side = "BOTH"
