modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
    modId = "cropaura"
    version = "1.0.0"
    displayName = "Crop Aura"
    description = '''
Automatically applies bonemeal to crops around the player.
    '''
    authors = "CropAura"

[[dependencies.cropaura]]
    modId = "forge"
    mandatory = true
    versionRange = "[36,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.cropaura]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.5,1.17)"
    ordering = "NONE"
    side = "BOTH"
